### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by 2505817596** [lucidcode/LucidScribe-Hypnodyne-ZMax#1]
I bought zmax for lucidming version, and when I use the LucidScribe-Hypnodyne-ZMax plugin, nothing happens? Can you update it? Thank you

**Comment by IAmCoder** [comment]
Thanks for testing! I've updated it. Can you try again with the latest release and let me know if it picks up the data feed: https://github.com/lucidcode/LucidScribe-Hypnodyne-ZMax/releases/tag/1.0.1

Make sure that HDServer.exe is running and let me know if it logs "Client connected" when you start Lucid Scribe.

**Comment by 2505817596** [comment]
It doesn't seem to be responding, but it shows Client connected, the other day I tried to get the parsed data directly from HDRecorder, Lucid Scribe for zmax should be displayed normally, but I want to know if the current algorithm is reliable, I am sleeping, there is no rem triggering
![image](https://github.com/lucidcode/LucidScribe-Hypnodyne-ZMax/assets/37748815/4bde2c0a-bfc1-4bf3-a473-b359cc44298e)

**Comment by IAmCoder** [comment]
Thanks for the quick test! Can you try again with and let me know if it picks up any signals:
https://github.com/lucidcode/LucidScribe-Hypnodyne-ZMax/releases/tag/1.0.2

**Comment by 2505817596** [comment]
No, still can't get any data, nothing is displayed

**Comment by IAmCoder** [comment]
I've added a data console in https://github.com/lucidcode/LucidScribe-Hypnodyne-ZMax/releases/tag/1.0.3 - does it show anything when you connect:
![image](https://github.com/lucidcode/LucidScribe-Hypnodyne-ZMax/assets/1631870/74642402-5df7-4856-8ab1-44ddf1bc5bc5)

**Comment by 2505817596** [comment]
yes
![image](https://github.com/lucidcode/LucidScribe-Hypnodyne-ZMax/assets/37748815/a330b1cf-f636-4129-90ce-4971c8c29583)

**Comment by IAmCoder** [comment]
Thanks. Are you connected with HDRecorder.exe?

**Comment by 2505817596** [comment]
Yes, connected

**Comment by IAmCoder** [comment]
Thanks for confirming. Are you able to pick up the signal with https://github.com/dreamento/dreamento

**Comment by 2505817596** [comment]
No,can't get any data
![image](https://github.com/lucidcode/LucidScribe-Hypnodyne-ZMax/assets/37748815/7bbbb788-c600-46cc-ad51-03fc1b33bbe0)

**Comment by 2505817596** [comment]
No,can't get any data
![image](https://github.com/lucidcode/LucidScribe-Hypnodyne-ZMax/assets/37748815/098efdc5-75df-45fc-839c-2d083b8e97b8)

**Comment by IAmCoder** [comment]
Interesting, thanks. It seems like HDRecorder isn't sending anything. When connected to HDServer, I'd expect it to send "idlemode" mesages:

![image](https://github.com/lucidcode/LucidScribe-Hypnodyne-ZMax/assets/1631870/d2bf67af-bc62-4ed5-8bfb-98786434e4f9)

**Comment by ChunkyToads** [comment]
When purchasing a Hypnodyne Zmax there are two pricing tiers... One for LDversion and one for TotalPackage ver ("connecting HD SERVER to your customers software")

 Is it possible OP simply doesn't have access to HD SERVER'S feed because of this? 

If so, wouldn't OP be limited to making adjustments through the code provided at purchase...and used via HDRecorder? Just a thought, perhaps laden with many incorrect assumptions on my part.

**Comment by IAmCoder** [comment]
Thanks toads, that must be it! When I made the plugin they didn't the pricing tiers.
